# Generated by Django 4.0.1 on 2022-01-14 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaypalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
