# Generated by Django 4.0.1 on 2022-01-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaypalApp', '0002_remove_lineitem_order_remove_lineitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(default='', max_length=200)),
                ('Price', models.CharField(max_length=100)),
            ],
        ),
    ]
