# Generated by Django 4.0.1 on 2022-01-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaypalApp', '0003_csv_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_model',
            name='Price',
            field=models.FloatField(),
        ),
    ]
