# Generated by Django 4.0.1 on 2022-01-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaypalApp', '0004_alter_csv_model_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSV_Model',
        ),
    ]
