# Generated by Django 4.0.1 on 2022-01-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaypalApp', '0005_delete_csv_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_item_id', models.IntegerField()),
                ('transaction_id', models.IntegerField()),
                ('transaction_status', models.CharField(default='', max_length=100)),
                ('currency', models.CharField(default='', max_length=100)),
                ('payout_fee', models.IntegerField()),
                ('payout_batch_id', models.IntegerField()),
                ('recipient_type', models.IntegerField()),
                ('recieving_amount', models.FloatField()),
                ('reciever_email', models.CharField(default='', max_length=100)),
                ('recipient_wallet', models.CharField(default='', max_length=100)),
                ('time_processed', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
