# Generated by Django 4.0.1 on 2022-01-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaypalApp', '0006_transactionsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsmodel',
            name='payout_batch_id',
            field=models.FloatField(),
        ),
    ]
