# Generated by Django 4.0.1 on 2022-01-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaypalApp', '0007_alter_transactionsmodel_payout_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionsmodel',
            name='recipient_type',
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='payout_fee',
            field=models.FloatField(),
        ),
    ]
