# Generated by Django 4.0.1 on 2022-01-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaypalApp', '0008_remove_transactionsmodel_recipient_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsmodel',
            name='payout_item_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='transaction_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
