# Generated by Django 4.0.1 on 2022-01-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaypalApp', '0012_alter_transactionsmodel_payout_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsmodel',
            name='recipient_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
